from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns 
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_request, name='AdminLogin'),
    path('logout/<templateview>/', views.logout_request, name='AdminLogOut'),
    path('add-manufacturer', views.add_manufacturer, name='AddNewManufacturer'),
    path('show-manufacturer', views.show_manufacturer, name='ShowManufacturer'),
    path('edit-manufacturer/<id>/', views.edit_manufacturer, name='EditManufacturer'),
    # path('delete-manufacturer/<id>/', views.delete_manufacturer, name='DeleteProject'),
    # path('show-manufacturer', views.show_manufacturer, name='ShowProject'),
    # path('single-manufacturer/<id>/', views.single_manufacturer, name='ShowSingleProject'),
    path('add-category', views.add_category, name='AddNewCategory'),
    path('show-product-categories', views.show_product_category, name='ShowProductCategory'),
    path('single-product-category/<id>/', views.single_product_category, name='ShowSingleProductCategory'),
    path('delete-product-category/<id>/', views.delete_product_category, name='delete_product_category'),
    path('edit-product-category/<id>/', views.edit_product_category, name='EditProductCategory'),
    path('adduser', views.add_user, name='AddNewUser'),
    path('showusers', views.show_users, name='Showusers'),
    path('showuser-role/<name>/', views.show_consumers, name='Showconsumers'),
    path('edit-user/<id>/', views.edit_user, name='EditUser'),
    path('edit-sme-user/<id>/', views.edit_sme_user, name='EditSmeUser'),
    path('show-concierge-manager', views.show_concierge_users, name='Showconcierge'),
    path('show-sale-representative', views.show_sales_user, name='ShowSalesusers'),
    path('deleteuser/<id>/', views.delete_user, name='DeleteUser'),
    path('userdetail/<id>/', views.userdetail, name='userdetail'),
    path('userdetail-others/<id>/<parent>/', views.userdetail_other, name='userdetailother'),
    path('signup', views.signup, name='backendsignup'),
    path('client_activate', views.client_activate, name='client_activate'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.client_activate, name='client_activate'),
    path('add-page', views.add_page, name='AddNewPage'),
    path('show-page', views.show_page, name='ShowPage'),
    path('single-page/<id>/', views.single_page, name='ShowSinglePage'),
    path('delete-single-page/<id>/', views.delete_single_page, name='DeleteSinglePage'),
    path('edit-single-page/<id>/', views.edit_single_page, name='EditSinglePage'),
    path('add-product', views.add_product, name='AddNewProduct'),
    path('show-product', views.show_product, name='ShowProduct'),
    path('single-product/<id>/', views.single_product, name='ShowSingleProduct'),
    path('edit-single-product/<id>/', views.edit_single_product, name='EditSingleProduct'),
    path('delete-single-product/<id>/', views.delete_single_product, name='DeleteSingleProduct'),
    path('add-rate', views.add_rate, name='AddNewRate'),
    path('edit-rate/<id>/', views.edit_rate, name='EditRate'),
    path('addtocart/', views.CreateCart, name='createcart'),
    path('cart-count/', views.cartcount, name='CartCount'),
    path('delete-cartitem/', views.DeleteCartItem, name='DeleteCartItem'),
    path('addtowishlist/', views.Wish, name='Wish'),
    path('wish-count/', views.wishcount, name='WishCount'),
    path('checkout/', views.Checkout, name='CheckOut'),
    path('stripebuy/', views.BuyProductUsingStripe, name='BuyProductUsingStripe'),
    path('product-filter/', views.productfilter, name='Productfilter'),
    path('add-attribute-label', views.add_attributelevel, name='addlevel'),
    path('show-attribute-label', views.show_attributelevel, name='Showattributelevel'),
    path('edit-attribute-label/<id>/', views.edit_attributelevel, name='Editattributelevel'),
    path('delete-attribute-label/<id>/', views.delete_attributelevel, name='delete_attributelevel'),
    path('add-attribute-property', views.add_attributeproperty, name='addproperty'),
    path('show-attribute-property', views.show_attributeproperty, name='Showattributeproperty'),
    path('edit-attribute-property/<id>/', views.edit_attributeproperty, name='Editattributeproperty'),
    path('delete-attribute-property/<id>/', views.delete_attributeproperty, name='delete_attributeproperty'),
    path('add-variant-to-product/<id>/', views.assign_variant, name='assignvariant'),
    path('connectstripe/', views.paystripe, name='connectstripe'),
    path('payto-stripe/', views.paytostripe, name='paytostripe'),
    path('total-price/', views.totalprice, name='totalprice'),
    url(r'^upload/csv/$', views.upload_csv, name='upload_csv'),
    path('all-order/', views.allorder, name='allorder'),
    path('order/<id>/', views.singleorder, name='singleorder'),
    path('allsmeorder/', views.allsmeorder, name='allsmeorder'),
    path('all-payout/', views.allpayout, name='allpayout'),
    path('user-payout/', views.ShowPayoutToManager, name='ShowPayoutToManager'),
    

    
]
