# Generated by Django 3.1.1 on 2020-09-09 06:00

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='Category-Preview')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Category_Name', unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Category-Banner')),
                ('priority_order', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('priority_order',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_Rate', models.IntegerField(help_text='Insert pointt convertsion rate to money (Only INT Like : 10 )')),
                ('Manufacturer_Rate', models.IntegerField(help_text='Insert start limits for converting points to money (Only INT Like : 100 )')),
                ('Sme_Rate', models.IntegerField(help_text='Insert last limits for converting points to money (Only INT Like : 100 )')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_Name', models.CharField(max_length=100)),
                ('Page_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('Banner_Image', models.ImageField(blank=True, null=True, upload_to='Page_Banner_Images')),
                ('Page_Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Page_Feautured_Image', models.ImageField(blank=True, null=True, upload_to='Page_Feautured_Images')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Page_Name', unique=True)),
                ('Status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], default='Publish', max_length=20)),
                ('Page_Role', models.CharField(choices=[('Content', 'Content'), ('About', 'About'), ('Contact', 'Contact'), ('Privacy', 'Privacy'), ('Partner', 'Partner'), ('Term', 'Term of use'), ('Return', 'Return Policy')], default=0, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100, null=True)),
                ('Product_Article_Number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Product_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Product_Preview_image', models.ImageField(blank=True, default='', null=True, upload_to='Product_image')),
                ('Product_Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Product_Name', unique=True)),
                ('Status', models.BooleanField(default=True)),
                ('priority_order', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categories')),
            ],
            options={
                'ordering': ('priority_order',),
            },
        ),
        migrations.CreateModel(
            name='ParentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currents', to=settings.AUTH_USER_MODEL)),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer_Name', models.CharField(max_length=100)),
                ('Manufacturer_Address', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Manufacturer_Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.country')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
