# Generated by Django 3.1.1 on 2020-09-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_attribute_attributebase_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Variant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.attribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='Shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='variant_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
