# Generated by Django 3.1.1 on 2020-10-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201010_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Type',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Gallery', to='backend.product'),
        ),
    ]
